apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
spec:
  replicas: 1 # number of pods that will run simultaneously
  selector:
    matchLabels:
      team: developer-mongodb
  template:
    metadata:
      name: pod-mongodb
      labels:
        team: developer-mongodb
    spec:
      containers:
        - name: container-mongodb
          image: mongo # (Docker Image ismidir. hub.docker.com'dan baktık)
          resources:
            limits:
              cpu: 400m
              memory: "1024Mi" # 1024Mi -> 1024 mb ram
          ports:
            - containerPort: 27017 # (hub.docker.com/_/mongo -> "Example docker-compose.yml for mongo" -> ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017 -> this port  )
          env:
            - name: MONGO_INITDB_ROOT_USERNAME # (hub.docker.com/_/mongo -> "Example docker-compose.yml for mongo")
              value: adminbilge
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Aa123456**