apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgres
spec:
  replicas: 1 # number of pods that will run simultaneously
  selector:
    matchLabels:
      team: developer-postgre
  template:
    metadata: # Pod_postgresql.yml'daki kodu buraya copy-paste yaptık (metadata ve aşağısını)
      name: pod-postgre
      labels:
        team: developer-postgre
        burayaetiketyaz: ne-yazmak-lazim
    spec:
      containers:
        - name: container-postgre
          image: postgres
          resources:
            limits:
              cpu: 400m
              memory: "1024Mi" # 1024Mi -> 1024 mb ram
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root