apiVersion: v1
kind: Pod
metadata:
  name: pod-postgre
  labels:
    team: developer-postgre
    burayaetiketyaz: ne-yazmak-lazim
spec:
  containers: # bir pod'un içine 1 tane container koyun, daha fazla koymayın. (örneğin postgre'yi koyun, başka bir şey koymayın)
  - name: container-postgre
    image: postgres
    resources:
      limits:
        cpu: 400m
        memory: "1024Mi" # 1024Mi -> 1024 mb ram
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: root
