apiVersion: v1
kind: Service
metadata:
  name: clusterip-auth
spec:
  selector:
    team: developer-auth # Deployment_auth_microservice.yml'de yazdığımız 'team'i yazıyoruz.
  type: ClusterIP
  ports:
    - name: auth
      port: 9090
      targetPort: 9090