apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-zipkin
spec:
  replicas: 1 # number of pods that will run simultaneously
  selector:
    matchLabels:
      team: developer-zipkin
  template:
    metadata:
      name: pod-zipkin
      labels:
        team: developer-zipkin
    spec:
      containers:
        - name: container-zipkin
          image: openzipkin/zipkin # (www.zipkin.io/pages/quickstart.html -> 'Docker' başlığı altında -> the command to run image: docker run -d -p 9411:9411 openzipkin/zipkin -> "openzipkin/zipkin")
          resources:
            limits:
              cpu: 200m
              memory: "1024Mi" # 1024Mi -> 1024 mb ram
          ports:
            - containerPort: 9411 # (www.zipkin.io/pages/quickstart.html)
          env:
            - name: MONGO_INITDB_ROOT_USERNAME # (hub.docker.com/_/mongo -> "Example docker-compose.yml for mongo")
              value: adminbilge
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Aa123456**
