apiVersion: v1
kind: Service
metadata:
  name: load-balancer-postgresql
spec:
  selector:
    team: developer-postgre # Deployment_postgresql.yml'de yazdığımız 'team'i yazıyoruz.
  type: LoadBalancer
  ports:
    - name: postgreports
      port: 11111
      targetPort: 5432