spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:" # configserver modülü içinde...
  application:
    name: user-service-application # bu dosyanın içinde - config ayarları.