server:
  port:7079

spring:
  elasticsearch:
    uris: http://localhost:9200
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

rabbitmq:
  exchange-user: user-exchange # --> this is a string value (to be used in RabbitMqConfig class)
  elasticregisterkey: elastic-register-key
  queueregisterelastic: elastic-register-queue
  queueRegister: register-queue