server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmetkarahasanoglu/config-server-repo-2-sosyalMedya-m-o-.git
          default-label: main
          skip-ssl-validation: true
          username: ahmetkarahasanoglu
          password: ${SosyalMedya(m.o)-ConfigServerPsw}