server:
  port: 7072
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
#  datasource:   # (bu kısmı Postgresql kullandığımız zaman kullandık, daha sonra sildik; ve aşağıdaki "data: mongodb" ayarlarını kullandık.
#    url: jdbc:postgresql://localhost:5432/java6USERDB
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: java6user
      password: root
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root

jwt:
  secretkey: ${java6secretkey} # (windows ortam değişkenleri'nden çekiyoruz)
  audience: ${java6audience}
  issuer: ${java6issuer}

rabbitmq:
  exchange-user: user-exchange # --> this is a string value (to be used in RabbitMqConfig class)
  elasticregisterkey: elastic-register-key
  queueregisterelastic: elastic-register-queue
  queueRegister: register-queue